### ISSUE TITLE
`SourceNode.children` type incorrect

### ISSUE THREAD

**Issue by siefkenj** [hildjj/source-map-generator#1]
According to 

https://github.com/hildjj/source-map-generator/blob/86391e61e7f261bed888ca59eef3d9fb713903b2/lib/source-node.js#L195

`SourceNode.children` should have a type `(SourceNode | string)[]`, but `source-map.d.ts` lists the type as `SourceNode[]`

**Comment by hildjj** [comment]
This is an issue in the upstream project, I think:

https://github.com/mozilla/source-map/blob/4e304db915cecd42505feb007766a034395c6eb7/source-map.d.ts#L384

**Comment by siefkenj** [comment]
Thanks, filed upstream.
